### ISSUE TITLE
assign(:x).with_a_new(Klass) should handle nil values

### ISSUE THREAD

**Issue by thomasfedb** [thomasfedb/warp#5]
```
undefined method `persisted?' for nil:NilClass
     # /home/thomasfedb/.rvm/gems/ruby-2.2.1@atlantis/gems/warp-1.3.2/lib/warp/controller_matchers/assign_matcher.rb:70:in `check_assign_with_a_new'
     # /home/thomasfedb/.rvm/gems/ruby-2.2.1@atlantis/gems/warp-1.3.2/lib/warp/controller_matchers/assign_matcher.rb:38:in `matches?'
```

**Comment by thomasfedb** [comment]
Fixed by f26547c.
